apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-amd64
spec:
  replicas: 3
  selector:
    matchLabels: { app: inflate-amd64 }
  template:
    metadata:
      labels: { app: inflate-amd64 }
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        karpenter.sh/capacity-type: spot
      containers:
        - name: pause
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.10
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
